### ISSUE TITLE
bug:项目down下来，报错 The element type 'QrImage' can't be assigned to the list type 'Widget'.

### ISSUE THREAD

**Issue by czeras** [LeeeYudE/flutter_wechat#1]
macos：13.2 (22D49)
xcode：14.3 (14E222b)

<img width="1578" alt="截屏2023-10-17 22 01 08" src="https://github.com/LeeeYudE/flutter_wechat/assets/35266402/66a4b1a8-0bba-40ea-9c70-1c945c8ea37b">

**Comment by LeeeYudE** [comment]
最近我刚升级到flutter3.10.0，版本有对应上嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月17日(周二) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeeeYudE/flutter_wechat] bug:项目down下来，报错 The element type 'QrImage' can't be assigned to the list type 'Widget'. (Issue #1)




 
macos：13.2 (22D49)
 xcode：14.3 (14E222b)

**Comment by czeras** [comment]
我晚上回家改下版本试试
