### ISSUE TITLE
能写代码注释就好了

### ISSUE THREAD

**Issue by JadeXH** [LeeeYudE/flutter_wechat#2]
再把项目结构介绍一下就更完美了。

**Comment by LeeeYudE** [comment]
多谢建议，有空我补一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 晚上9:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeeeYudE/flutter_wechat] 能写代码注释就好了 (Issue #2)




 
再把项目结构介绍一下就更完美了。
