### ISSUE TITLE
问一下关于输入框底部的工具栏切换相关问题。

### ISSUE THREAD

**Issue by YeFei572** [LeeeYudE/flutter_wechat#3]
大佬你好，
看了一下当前项目，完成度很高，有个地方想请教一下：
我自己copy了代码，为啥弹出的效果是这样的？ 是不是有跟原生做交互的关系呢？
![image](https://github.com/LeeeYudE/flutter_wechat/assets/26360338/568dcb9e-00b9-4be4-a1d4-81b7d4cc5525)
主要代码如下：
```dart
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('烧饼', style: TextStyle(color: Colors.white)),
        backgroundColor: const Color(0xff1E1E3F),
      ),
      body: Column(
        children: [
          /// 构造聊天内容
          Expanded(
            child: Container(color: const Color(0xff2D2B55)),
          ),
          const ChatInputWidget(),
        ],
      ),
    );
  }
}
```
ChatInputWidget
```dart
import 'package:demo15/ext/decoration_ext.dart';
import 'package:demo15/ext/size_box_ext.dart';
import 'package:demo15/ext/widget_ext.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:sp_util/sp_util.dart';

import '../color/colors.dart';
import 'chat_more_panel.dart';
import 'input_field.dart';
import 'send_message_btn.dart';
import 'subscription_mixin.dart';
import 'tap_widget.dart';
import 'utils.dart';

class ChatInputWidget extends StatefulWidget {
  const ChatInputWidget({Key? key}) : super(key: key);

  @override
  State<ChatInputWidget> createState() => _ChatInputWidgetState();
}

class _ChatInputWidgetState extends State<ChatInputWidget>
    with WidgetsBindingObserver, SubscriptionMixin {
  static const int INPUT_TYPE_NULL = 0;
  static const int INPUT_TYPE_EMOJI = 1;
  static const int INPUT_TYPE_AUDIO = 2;
  static const int INPUT_TYPE_MORE = 3;

  final FocusNode focusNode = FocusNode();
  // final ChatController _chatController = Get.find();

  final TextEditingController textController = TextEditingController();

  double _keyboardHeight = 0;
  //是否键盘弹出
  bool isKeyboard = false;
  bool autoShowKeyboard = false;
  int inputType = INPUT_TYPE_NULL;

  @override
  initState() {
    super.initState();
    _init();
  }

  void _init() async {
    WidgetsBinding.instance.addObserver(this);
    _keyboardHeight = SpUtil.getDouble('keyboardHeight', defValue: 310.w)!;
  }

  @override
  void didChangeMetrics() {
    super.didChangeMetrics();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        if (!(ModalRoute.of(context)?.isCurrent ?? true)) {
          if (isKeyboard) {
            onKeyboardHeight(0);
            FocusScope.of(context).requestFocus(FocusNode());
          }
          return;
        }
        final bottom = MediaQuery.of(context).viewInsets.bottom;
        onKeyboardHeight(bottom);
      }
    });
  }

  void onKeyboardHeight(double height) {
    // debugPrint("onKeyboardHeight $isKeyboard $height $_keyboardHeight");
    if (height == 0) {
      //关闭键盘
      if (isKeyboard) {
        setState(() {
          isKeyboard = false;
        });
      }
    } else {
      if (height < _keyboardHeight) {
        return;
      }
      autoShowKeyboard = false;
      _keyboardHeight = height;
      setState(() {
        inputType = INPUT_TYPE_NULL;
        isKeyboard = true;
      });
      SpUtil.putDouble('keyboardHeight', _keyboardHeight);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Colours.c_CCCCCC.toLine(1.w),
        _buildInputLayout(),
        Colours.c_CCCCCC.toLine(1.w),
        _buildBottomPanel()
      ],
    );
  }

  _buildInputLayout() {
    return TapWidget(
      onTap: () {},
      child: Container(
        color: Colours.c_F7F7F7,
        padding: EdgeInsets.symmetric(horizontal: 10.w, vertical: 10.w),
        child: Row(
          children: [
            // _buildInputType(),
            // 20.sizedBoxW,
            Expanded(
              child: InputField(
                autofocus: false,
                focusNode: focusNode,
                controller: textController,
                extended: true,
              ),
            ),
            20.sizedBoxW,
            // _buildInputEmoji(),
            // 20.sizedBoxW,
            _buildInputMore()
          ],
        ),
      ),
    );
  }

  _buildInputMore() {
    return Stack(
      alignment: Alignment.center,
      children: [
        TapWidget(
            onTap: () {
              _clickInputBtn(INPUT_TYPE_MORE);
              setState(() {});
            },
            child: Image.asset(
              Utils.getImgPath('ic_chat_more',
                  dir: Utils.DIR_CHAT, format: Utils.WEBP),
              width: 42.w,
              height: 42.w,
              color: Colours.black,
            )),
        SendMessageBtn(textController: textController),
      ],
    );
  }

  _buildInputType() {
    return TapWidget(
        onTap: () {
          _clickInputBtn(INPUT_TYPE_AUDIO);
        },
        child: Image.asset(
            Utils.getImgPath(
                inputType == INPUT_TYPE_AUDIO ? 'ic_keyboard' : 'ic_voice',
                dir: Utils.DIR_CHAT,
                format: Utils.WEBP),
            width: 60.w,
            height: 60.w,
            color: Colours.black,
            fit: BoxFit.fill));
  }

  _buildInputEmoji() {
    return TapWidget(
        onTap: () {
          _clickInputBtn(INPUT_TYPE_EMOJI);
        },
        child: Image.asset(
          Utils.getImgPath('ic_emotion',
              dir: Utils.DIR_CHAT, format: Utils.WEBP),
          width: 60.w,
          height: 60.w,
          color: Colours.black,
          fit: BoxFit.fill,
        ));
  }

  _clickInputBtn(int inputType) {
    setState(() {
      if (this.inputType == inputType) {
        this.inputType = INPUT_TYPE_NULL;
        WidgetsBinding.instance
            .addPostFrameCallback((_) => focusNode.showkeyboard());
        autoShowKeyboard = true;
      } else {
        this.inputType = inputType;
        if (isKeyboard) {
          _hidekeyboard();
        }
        if (inputType != INPUT_TYPE_EMOJI) {
          focusNode.unfocus();
        }
      }
    });
  }

  _hidekeyboard() {
    SystemChannels.textInput
        .invokeMethod<void>('TextInput.hide')
        .whenComplete(() {});
  }

  _buildBottomPanel() {
    // debugPrint('_buildBottomPanel $isKeyboard $inputType ');
    if ((!isKeyboard && inputType == INPUT_TYPE_NULL && !autoShowKeyboard) ||
        inputType == INPUT_TYPE_AUDIO) {
      return Container();
    }
    Widget? child;
    if (inputType == INPUT_TYPE_MORE) {
      child = ChatMorePanel();
    } else if (inputType == INPUT_TYPE_EMOJI) {
      // child = EmojiGridView(
      //   onTap: (EmojiModel emoji) {
      //     insertText(emoji.tag!);
      //   },
      // );
      child = Center(
        child: Text('表情包'),
      );
    }
    return SizedBox(
      height: _keyboardHeight,
      child: child,
    );
  }

  void insertText(String text) {
    textController.insertText(text);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```

**Comment by LeeeYudE** [comment]
你把Scaffold.resizeToAvoidBottomInset改成false试试
你把Scaffold.resizeToAvoidBottomInset改成false试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeeeYudE/flutter_wechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上9:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LeeeYudE/flutter_wechat] 问一下关于输入框底部的工具栏切换相关问题。 (Issue #3)





 
大佬你好，
 看了一下当前项目，完成度很高，有个地方想请教一下：
 我自己copy了代码，为啥弹出的效果是这样的？ 是不是有跟原生做交互的关系呢？
 
 主要代码如下：
 class HomePage extends StatefulWidget {   const HomePage({super.key});   @override   State<HomePage&gt; createState() =&gt; _HomePageState(); } class _HomePageState extends State<HomePage&gt; {   @override   Widget build(BuildContext context) {     return Scaffold(       appBar: AppBar(         title: const Text('烧饼', style: TextStyle(color: Colors.white)),         backgroundColor: const Color(0xff1E1E3F),       ),       body: Column(         children: [           /// 构造聊天内容           Expanded(             child: Container(color: const Color(0xff2D2B55)),           ),           const ChatInputWidget(),         ],       ),     );   } }
 
ChatInputWidget
 import 'package:demo15/ext/decoration_ext.dart'; import 'package:demo15/ext/size_box_ext.dart'; import 'package:demo15/ext/widget_ext.dart'; import 'package:flutter/material.dart'; import 'package:flutter/services.dart'; import 'package:flutter_screenutil/flutter_screenutil.dart'; import 'package:sp_util/sp_util.dart'; import '../color/colors.dart'; import 'chat_more_panel.dart'; import 'input_field.dart'; import 'send_message_btn.dart'; import 'subscription_mixin.dart'; import 'tap_widget.dart'; import 'utils.dart'; class ChatInputWidget extends StatefulWidget {   const ChatInputWidget({Key? key}) : super(key: key);   @override   State<ChatInputWidget&gt; createState() =&gt; _ChatInputWidgetState(); } class _ChatInputWidgetState extends State<ChatInputWidget&gt;     with WidgetsBindingObserver, SubscriptionMixin {   static const int INPUT_TYPE_NULL = 0;   static const int INPUT_TYPE_EMOJI = 1;   static const int INPUT_TYPE_AUDIO = 2;   static const int INPUT_TYPE_MORE = 3;   final FocusNode focusNode = FocusNode();   // final ChatController _chatController = Get.find();   final TextEditingController textController = TextEditingController();   double _keyboardHeight = 0;   //是否键盘弹出   bool isKeyboard = false;   bool autoShowKeyboard = false;   int inputType = INPUT_TYPE_NULL;   @override   initState() {     super.initState();     _init();   }   void _init() async {     WidgetsBinding.instance.addObserver(this);     _keyboardHeight = SpUtil.getDouble('keyboardHeight', defValue: 310.w)!;   }   @override   void didChangeMetrics() {     super.didChangeMetrics();     WidgetsBinding.instance.addPostFrameCallback((_) {       if (mounted) {         if (!(ModalRoute.of(context)?.isCurrent ?? true)) {           if (isKeyboard) {             onKeyboardHeight(0);             FocusScope.of(context).requestFocus(FocusNode());           }           return;         }         final bottom = MediaQuery.of(context).viewInsets.bottom;         onKeyboardHeight(bottom);       }     });   }   void onKeyboardHeight(double height) {     // debugPrint("onKeyboardHeight $isKeyboard $height $_keyboardHeight");     if (height == 0) {       //关闭键盘       if (isKeyboard) {         setState(() {           isKeyboard = false;         });       }     } else {       if (height < _keyboardHeight) {         return;       }       autoShowKeyboard = false;       _keyboardHeight = height;       setState(() {         inputType = INPUT_TYPE_NULL;         isKeyboard = true;       });       SpUtil.putDouble('keyboardHeight', _keyboardHeight);     }   }   @override   Widget build(BuildContext context) {     return Column(       mainAxisSize: MainAxisSize.min,       children: [         Colours.c_CCCCCC.toLine(1.w),         _buildInputLayout(),         Colours.c_CCCCCC.toLine(1.w),         _buildBottomPanel()       ],     );   }   _buildInputLayout() {     return TapWidget(       onTap: () {},       child: Container(         color: Colours.c_F7F7F7,         padding: EdgeInsets.symmetric(horizontal: 10.w, vertical: 10.w),         child: Row(           children: [             // _buildInputType(),             // 20.sizedBoxW,             Expanded(               child: InputField(                 autofocus: false,                 focusNode: focusNode,                 controller: textController,                 extended: true,               ),             ),             20.sizedBoxW,             // _buildInputEmoji(),             // 20.sizedBoxW,             _buildInputMore()           ],         ),       ),     );   }   _buildInputMore() {     return Stack(       alignment: Alignment.center,       children: [         TapWidget(             onTap: () {               _clickInputBtn(INPUT_TYPE_MORE);               setState(() {});             },             child: Image.asset(               Utils.getImgPath('ic_chat_more',                   dir: Utils.DIR_CHAT, format: Utils.WEBP),               width: 42.w,               height: 42.w,               color: Colours.black,             )),         SendMessageBtn(textController: textController),       ],     );   }   _buildInputType() {     return TapWidget(         onTap: () {           _clickInputBtn(INPUT_TYPE_AUDIO);         },         child: Image.asset(             Utils.getImgPath(                 inputType == INPUT_TYPE_AUDIO ? 'ic_keyboard' : 'ic_voice',                 dir: Utils.DIR_CHAT,                 format: Utils.WEBP),             width: 60.w,             height: 60.w,             color: Colours.black,             fit: BoxFit.fill));   }   _buildInputEmoji() {     return TapWidget(         onTap: () {           _clickInputBtn(INPUT_TYPE_EMOJI);         },         child: Image.asset(           Utils.getImgPath('ic_emotion',               dir: Utils.DIR_CHAT, format: Utils.WEBP),           width: 60.w,           height: 60.w,           color: Colours.black,           fit: BoxFit.fill,         ));   }   _clickInputBtn(int inputType) {     setState(() {       if (this.inputType == inputType) {         this.inputType = INPUT_TYPE_NULL;         WidgetsBinding.instance             .addPostFrameCallback((_) =&gt; focusNode.showkeyboard());         autoShowKeyboard = true;       } else {         this.inputType = inputType;         if (isKeyboard) {           _hidekeyboard();         }         if (inputType != INPUT_TYPE_EMOJI) {           focusNode.unfocus();         }       }     });   }   _hidekeyboard() {     SystemChannels.textInput         .invokeMethod<void&gt;('TextInput.hide')         .whenComplete(() {});   }   _buildBottomPanel() {     // debugPrint('_buildBottomPanel $isKeyboard $inputType ');     if ((!isKeyboard &amp;&amp; inputType == INPUT_TYPE_NULL &amp;&amp; !autoShowKeyboard) ||         inputType == INPUT_TYPE_AUDIO) {       return Container();     }     Widget? child;     if (inputType == INPUT_TYPE_MORE) {       child = ChatMorePanel();     } else if (inputType == INPUT_TYPE_EMOJI) {       // child = EmojiGridView(       //   onTap: (EmojiModel emoji) {       //     insertText(emoji.tag!);       //   },       // );       child = Center(         child: Text('表情包'),       );     }     return SizedBox(       height: _keyboardHeight,       child: child,     );   }   void insertText(String text) {     textController.insertText(text);   }   @override   void dispose() {     WidgetsBinding.instance.removeObserver(this);     super.dispose();   } }

**Comment by YeFei572** [comment]
大佬就是大佬
我居然忘记这个了，一时糊涂了。。
多谢提点。

**Comment by YeFei572** [comment]
还有个问题请教一下，为啥发送按钮和moreIcon要用Stack包裹？这样点击效果好像并不怎么样，有时候点击好像还会失效。
